---
title: "test"
author: "Shuxiang"
date: "2024-04-09"
output: html_document
---

```{r}
library("haven")
library("ggplot2")
library("patchwork")
library("dplyr")
library("R.utils")
library("parallel")
options(scipen=999)
cluster.num <- 20 # might need to check this (number of cpu threads)
```

```{r}
r_output <- pgyi.compiledstratified

sas_output <- fread("H:/Shared drives/Growth & Yield Lab/Data Sets/PGYI/2023-09-08 PGYI Compiled/3_final/PGYIcompiledstratified.csv")

treelist_output <- fread("H:/Shared drives/Growth & Yield Lab/Data Sets/PGYI/2023-09-08 PGYI Compiled/2_interim/tree_list1.csv")
```

```{r}

test_sas <- sas_output %>%
  filter(vol_0000 > 0.0001,
         scale == "spp_grp") %>%
  select(
   company, plot, mmt_num, mmt_yr, age, species, stand_type, sphRegenOnly, sphBH, ba, vol_0000, vol_1307, vol_1510
  ) %>%
  # group_by(company, plot, mmt_num, mmt_yr, age, stand_type) %>%
  # summarise(
  #   sphRegenOnly = mean(sphRegenOnly, na.rm = TRUE),
  #   sphBH = mean(sphBH, na.rm = TRUE),
  #   sphD15 = mean(sphD15, na.rm = TRUE),
  #   sphD91 = mean(sphD91, na.rm = TRUE),
  #   ba = mean(ba, na.rm = TRUE),
  #   vol_0000 = mean(vol_0000, na.rm = TRUE),
  #   vol_1307 = mean(vol_1307, na.rm = TRUE),
  #   vol_1510 = mean(vol_1510, na.rm = TRUE),
  #   biomass = mean(biomass, na.rm = TRUE),
  #   carbon = mean(carbon, na.rm = TRUE)
  #   # topht_n = mean(topht_n, na.rm = TRUE),
  #   # topht = mean(topht, na.rm = TRUE),
  #   # topht_stat = first(topht_stat, na.rm = TRUE)
  # )%>%
  filter_all(all_vars(!is.infinite(.) & !is.na(.)))
  
test_r <- r_output %>%
  filter(vol_0000 > 0.0001,
         scale == "spp_grp") %>%
  select(
   company, plot, mmt_num, mmt_yr, age, species, stand_type, sphRegenOnly, sphBH, ba, vol_0000, vol_1307, vol_1510
  ) %>%
  # group_by(company, plot, mmt_num, mmt_yr, age, stand_type) %>%
  # summarise(
  #   sphRegenOnly = mean(sphRegenOnly, na.rm = TRUE),
  #   sphBH = mean(sphBH, na.rm = TRUE),
  #   sphD15 = mean(sphD15, na.rm = TRUE),
  #   sphD91 = mean(sphD91, na.rm = TRUE),
  #   ba = mean(ba, na.rm = TRUE),
  #   vol_0000 = mean(vol_0000, na.rm = TRUE),
  #   vol_1307 = mean(vol_1307, na.rm = TRUE),
  #   vol_1510 = mean(vol_1510, na.rm = TRUE),
  #   biomass = mean(biomass, na.rm = TRUE),
  #   carbon = mean(carbon, na.rm = TRUE)
  #   # topht_n = mean(topht_n, na.rm = TRUE),
  #   # topht = mean(topht, na.rm = TRUE),
  #   # topht_stat = first(topht_stat, na.rm = TRUE)
  # ) %>%
  filter_all(all_vars(!is.infinite(.) & !is.na(.)))

diff_1 <- anti_join(test_sas, test_r, by = c("company", "plot", "mmt_num", "mmt_yr", "stand_type"))
diff_2 <- anti_join(test_sas, test_r, by = c("company", "plot", "mmt_num", "mmt_yr", "stand_type"))

test_r_removed <- anti_join(test_r, diff_1,by = c("company", "plot", "mmt_num", "mmt_yr", "stand_type"))
test_sas_removed <- anti_join(test_sas, diff_2,by = c("company", "plot", "mmt_num", "mmt_yr", "stand_type"))

summary(test_r_removed)
summary(test_sas_removed)
  
  
```  

```{r}
test_visual <- test_sas_removed %>%
  left_join(test_r_removed, by = c("company", "plot", "mmt_num", "mmt_yr", "species", "stand_type")) %>%
  filter_all(all_vars(!is.infinite(.) & !is.na(.))) %>%
  rename_with(~sub("\\.x$", ".sas", .), ends_with(".x")) %>%
  rename_with(~sub("\\.y$", ".r", .), ends_with(".y")) %>%
  mutate(
    sphregen_diff = sphRegenOnly.sas / sphRegenOnly.r,
    sphBH_diff = sphBH.sas / sphBH.r,
    vol_diff = vol_0000.sas - vol_0000.r,
    ba_diff = ba.sas - ba.r
  )

density_regen <- ggplot(test_visual, aes(x = sphRegenOnly.sas, y = sphRegenOnly.r, color = company)) +
  geom_point(alpha = 0.5, size = 2) +
  labs(x = "Regen Density by SAS (trees/ha)",
       y = "Regen Density by R (trees/ha)") 
  
density <- ggplot(test_visual, aes(x = sphBH.sas, y = sphBH.r, color = company)) +
  geom_point(alpha = 0.5, size = 2) +
  labs(x = "Density by SAS (trees/ha)",
       y = "Density by R (trees/ha)") 
 
ba <- ggplot(test_visual, aes(x = ba.sas, y = ba.r, color = company)) +
  geom_point(alpha = 0.5, size = 2) +
  labs(x = "Basal Area by SAS (m2/ha)",
       y = "Basal Area by SAS (m2/ha)")  
 
total_vol <- ggplot(test_visual, aes(x = vol_0000.sas, y = vol_0000.r, color = company)) +
  geom_point(alpha = 0.5, size = 2) +
  labs(x = "Total Volume by SAS (m続/ha)",
       y = "Total Volume by R (m続/ha)")  

merc_vol <- ggplot(test_visual, aes(x = vol_1510.sas, y = vol_1510.r, color = company)) +
  geom_point(alpha = 0.5, size = 2) +
  labs(x = "Total Merch by R (m続/ha)",
       y = "Total Merch by R (m続/ha)")  

print(density_regen)
print(density)
print(ba)
print(total_vol)
print(merc_vol)
```

```{r}
ggsave(
  "density_regen.png",
  plot = density_regen,
  path = "H:/Shared drives/Model Comparison/Compilation_Code_R/Figures",
  width = 10,
  height = 6,
  units = "in"
)

ggsave(
  "density.png",
  plot = density,
  path = "H:/Shared drives/Model Comparison/Compilation_Code_R/Figures",
  width = 10,
  height = 6,
  units = "in"
)

ggsave(
  "ba.png",
  plot = ba,
  path = "H:/Shared drives/Model Comparison/Compilation_Code_R/Figures",
  width = 10,
  height = 6,
  units = "in"
)

ggsave(
  "total_vol.png",
  plot = total_vol,
  path = "H:/Shared drives/Model Comparison/Compilation_Code_R/Figures",
  width = 10,
  height = 6,
  units = "in"
)

ggsave(
  "merc_vol.png",
  plot = merc_vol,
  path = "H:/Shared drives/Model Comparison/Compilation_Code_R/Figures",
  width = 10,
  height = 6,
  units = "in"
)

```

```{r}
metrics <- test_visual %>%
  group_by(species) %>%
  summarise(
    N = n(),
    BA_Error = mean(ba.sas - ba.r, na.rm = TRUE)/mean(ba.sas),
    Density_Error = mean(sphBH.sas - sphBH.r, na.rm = TRUE)/mean(sphBH.sas),
    Total_vol_Error = mean(vol_0000.sas - vol_0000.r, na.rm = TRUE)/mean(vol_0000.sas),
    Merc_vol_Error = mean(vol_1510.sas - vol_1510.r, na.rm = TRUE)/mean(vol_1510.sas))%>%
  bind_rows(
   test_visual %>%
      summarise(
        species = "Total",
              N = n(),
    BA_Error = mean(ba.sas - ba.r, na.rm = TRUE)/mean(ba.sas),
    Density_Error = mean(sphBH.sas - sphBH.r, na.rm = TRUE)/mean(sphBH.sas),
    Total_vol_Error = mean(vol_0000.sas - vol_0000.r, na.rm = TRUE)/mean(vol_0000.sas),
    Merc_vol_Error = mean(vol_1510.sas - vol_1510.r, na.rm = TRUE)/mean(vol_1510.sas)
    )
  )

print(metrics)

fwrite(metrics,
 file="H:/Shared drives/Model Comparison/Compilation_Code_R/Figures/results.csv") 

```

```{r}

stem <- fread("H:/Shared drives/Growth & Yield Lab/Data Sets/PGYI/2023-09-08 PGYI Compiled/2_interim/plot_level1.csv")

stem_map <- stem %>%
  group_by(
    company, company_plot_number, plot_program, measurement_year, plot_type) %>% 
  summarise(
    plot_type = first(plot_type, na.rm = TRUE)) %>%
  rename(
    plot = company_plot_number,
    mmt_yr = measurement_year
  )


pgyi <- fread( "H:/Shared drives/Growth & Yield Lab/Data Sets/PGYI/2023-09-08 PGYI Compiled/3_final/PGYIcompiledstratified.csv")
psp <- pgyi %>%
  filter(
    plot_type == 3,
    mmt_yr %in% c(2012, 2013, 2014, 2022, 2023),
    plot_program != "MPB",
    scale == "spp_grp",
    strata %in% c("Pl", "PlHw")
  ) 

write.csv(psp,
 file="H:/Shared drives/Model Comparison/All Stands/GYPSY/stem_mapped_psp.csv") 
# write.csv(psp,
#  file="H:/Shared drives/Model Comparison/All Stands/GYPSY/stem_mapped_psp.csv")


psp_2 <- pgyi.compiledstratified %>%
  left_join(stem_map, by = c("company", "plot", "mmt_yr", "plot_type")) %>%
  filter(
    plot_type == 3,
    mmt_yr %in% c(2012, 2013, 2014, 2022, 2023, 2024),
    plot_program != "MPB",
    scale == "spp_grp",
    strata %in% c("Pl", "PlHw") 
  ) 

```